// Mock data for TurnoCero designs

const MOCK_TABLES = [
  {
    id: "t1",
    game: "Terraforming Mars",
    host: "martina_v",
    hostAvatar: "M",
    date: "Vie 15 May · 19:30",
    dateShort: "15 MAY",
    weekday: "VIE",
    time: "19:30",
    location: "Café Rivas, Palermo",
    players: 3,
    maxPlayers: 5,
    seats: 2,
    privacy: "public",
    joined: false,
    hosted: false,
    description: "Partida tranqui, llevo expansiones. Bienvenidos novatos.",
    tags: ["Estrategia", "Largo", "120-180min"],
    seed: 7,
  },
  {
    id: "t2",
    game: "Catan",
    host: "fede.ok",
    hostAvatar: "F",
    date: "Sab 16 May · 21:00",
    dateShort: "16 MAY",
    weekday: "SAB",
    time: "21:00",
    location: "Casa de Fede, Caballito",
    players: 3,
    maxPlayers: 3,
    seats: 0,
    privacy: "public",
    joined: true,
    hosted: false,
    description: "La revancha. Esta vez sin alianzas, palabra.",
    tags: ["Clásico", "Medio", "60-90min"],
    seed: 2,
  },
  {
    id: "t3",
    game: "Gloomhaven",
    host: "sofi.dice",
    hostAvatar: "S",
    date: "Dom 17 May · 16:00",
    dateShort: "17 MAY",
    weekday: "DOM",
    time: "16:00",
    location: "Club Newton, San Telmo",
    players: 2,
    maxPlayers: 4,
    seats: 2,
    privacy: "private",
    joined: false,
    hosted: false,
    description: "Campaña en curso — escenario 14. Buscamos un guerrero.",
    tags: ["Campaña", "Coop", "240min+"],
    seed: 11,
  },
  {
    id: "t4",
    game: "Wingspan",
    host: "martina_v",
    hostAvatar: "M",
    date: "Mar 19 May · 20:00",
    dateShort: "19 MAY",
    weekday: "MAR",
    time: "20:00",
    location: "Bar Notable, Almagro",
    players: 1,
    maxPlayers: 4,
    seats: 3,
    privacy: "public",
    joined: false,
    hosted: true,
    description: "",
    tags: ["Engine builder", "Medio", "70min"],
    seed: 4,
  },
  {
    id: "t5",
    game: "Root",
    host: "leo.meeple",
    hostAvatar: "L",
    date: "Jue 21 May · 19:00",
    dateShort: "21 MAY",
    weekday: "JUE",
    time: "19:00",
    location: "Tribunales",
    players: 4,
    maxPlayers: 4,
    seats: 0,
    privacy: "public",
    joined: false,
    hosted: false,
    description: "",
    tags: ["Asimétrico", "Conflicto", "90-120min"],
    seed: 8,
  },
  {
    id: "t6",
    game: "Spirit Island",
    host: "cami.r",
    hostAvatar: "C",
    date: "Sab 23 May · 17:00",
    dateShort: "23 MAY",
    weekday: "SAB",
    time: "17:00",
    location: "Villa Crespo",
    players: 1,
    maxPlayers: 3,
    seats: 2,
    privacy: "public",
    joined: false,
    hosted: false,
    description: "Difficulty 4. Que sepan jugar al menos básico.",
    tags: ["Coop", "Difícil", "120min"],
    seed: 5,
  },
];

const MOCK_MESSAGES = [
  {
    id: "m1",
    author: "fede.ok",
    avatar: "F",
    text: "¿Llevo algo de tomar?",
    time: "20:42",
    own: false,
  },
  {
    id: "m2",
    author: "martina_v",
    avatar: "M",
    text: "Yo llevo cerveza. Y galletitas saladas.",
    time: "20:44",
    own: false,
  },
  {
    id: "m3",
    author: "you",
    avatar: "Y",
    text: "Perfecto. Llevo el juego y dados extra por si acaso 🎲",
    time: "20:45",
    own: true,
  },
  {
    id: "m4",
    author: "fede.ok",
    avatar: "F",
    text: "Genia. ¿Empezamos puntual 21hs?",
    time: "20:46",
    own: false,
  },
  {
    id: "m5",
    author: "you",
    avatar: "Y",
    text: "Sí, dale. Que después no se hace de noche.",
    time: "20:47",
    own: true,
  },
];

const MOCK_PLAYERS = [
  { name: "martina_v", avatar: "M", host: true },
  { name: "fede.ok", avatar: "F", host: false },
  { name: "you", avatar: "Y", host: false, you: true },
];

const MOCK_RATINGS = [
  {
    user: "fede.ok",
    avatar: "F",
    score: 5,
    text: "Una de las mejores partidas. Repetimos pronto.",
  },
  {
    user: "martina_v",
    avatar: "M",
    score: 4,
    text: "Muy buena onda, faltó tiempo para terminar bien.",
  },
];

window.MOCK_TABLES = MOCK_TABLES;
window.MOCK_MESSAGES = MOCK_MESSAGES;
window.MOCK_PLAYERS = MOCK_PLAYERS;
window.MOCK_RATINGS = MOCK_RATINGS;
